---
- name: Example | Topic JSON Assignment for Draining Brokers
  hosts: 127.0.0.1
  roles:
    - name: kafka_lib
  post_tasks:
    - name: "Create topic 'test-topic-json-assignment'"
      kafka_topic:
        api_version: "2.6.0"
        name: "test-topic-json-assignment"
        partitions: 3
        replica_factor: 2
        bootstrap_servers: "localhost:9092,localhost:9093,localhost:9094"
        state: "present"

    - name: "Apply JSON assignment to drain broker 1003"
      kafka_topic:
        api_version: "2.6.0"
        name: "test-topic-json-assignment"
        bootstrap_servers: "localhost:9092,localhost:9093,localhost:9094"
        state: "present"
        json_assignment: 
          partitions:
            - topic: "test-topic-json-assignment"
              partition: 0
              replicas: [1001, 1002]
            - topic: "test-topic-json-assignment"
              partition: 1
              replicas: [1001, 1002]
            - topic: "test-topic-json-assignment"
              partition: 2
              replicas: [1001, 1002]

    - name: "Get topics information after assignment"
      kafka_info:
        resource: "topic"
        api_version: "2.6.0"
        bootstrap_servers: "localhost:9092"
      register: topics

    - name: "Display results"
      debug:
        var: topics['ansible_module_results']['test-topic-json-assignment']